#!/usr/bin/env python3
"""
Generate HTML show notes page for a broadcast.

Produces a responsive HTML page with:
- Embedded audio player
- Full transcript organized by segment/correspondent
- Hyperlinked citations
- Clean styling

Usage:
    ./generate_show_notes.py --manifest scripts/2026-03-14/manifest.json \
        --audio daily-news/2026-03-14.mp3 \
        --output daily-news/2026-03-14.html
"""

import argparse
import json
import os
import sys
from datetime import date
from html import escape

# Character display info
CHARACTERS = {
    "shovel": {"name": "Shovel", "role": "Host", "color": "#2563eb"},
    "nova": {"name": "Nova", "role": "Tech", "color": "#7c3aed"},
    "jessica": {"name": "Jessica", "role": "International", "color": "#059669"},
    "george": {"name": "George", "role": "Politics", "color": "#dc2626"},
    "fable": {"name": "Fable", "role": "Law & Business", "color": "#d97706"},
    "puck": {"name": "Puck", "role": "Quirky", "color": "#ec4899"},
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shovel News — {date}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       background: #0f172a; color: #e2e8f0; line-height: 1.6; }}
.container {{ max-width: 720px; margin: 0 auto; padding: 1.5rem; }}
header {{ text-align: center; padding: 2rem 0 1rem; border-bottom: 1px solid #1e293b; margin-bottom: 1.5rem; }}
h1 {{ font-size: 1.8rem; color: #f8fafc; margin-bottom: 0.3rem; }}
.date {{ color: #94a3b8; font-size: 1rem; }}
.player {{ background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 2rem; }}
.player audio {{ width: 100%; }}
.player-label {{ color: #94a3b8; font-size: 0.85rem; margin-bottom: 0.5rem; }}
.segment {{ margin-bottom: 1.5rem; padding: 1rem 1.25rem; background: #1e293b;
            border-radius: 8px; border-left: 4px solid #475569; }}
.segment-header {{ display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.5rem; }}
.character-name {{ font-weight: 700; font-size: 1rem; }}
.character-role {{ color: #94a3b8; font-size: 0.85rem; }}
.segment-text {{ color: #cbd5e1; font-size: 0.95rem; white-space: pre-line; }}
.sources {{ margin-top: 0.75rem; padding-top: 0.5rem; border-top: 1px solid #334155; }}
.sources-label {{ font-size: 0.75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.25rem; }}
.source-link {{ color: #60a5fa; font-size: 0.85rem; text-decoration: none; display: block; margin-bottom: 0.15rem; }}
.source-link:hover {{ text-decoration: underline; }}
footer {{ text-align: center; padding: 2rem 0; color: #475569; font-size: 0.8rem; border-top: 1px solid #1e293b; margin-top: 2rem; }}
</style>
</head>
<body>
<div class="container">
<header>
<h1>Shovel News</h1>
<div class="date">{date_display}</div>
</header>

<div class="player">
<div class="player-label">Listen to this broadcast</div>
<audio controls preload="metadata">
<source src="{audio_url}" type="audio/mpeg">
Your browser does not support the audio element.
</audio>
</div>

{segments_html}

<footer>
Generated by ClawCast — AI-powered news podcast<br>
Script: Qwen3.5-27B &middot; Voice: Kokoro TTS
</footer>
</div>
</body>
</html>"""


def generate_segment_html(seg, script_dir):
    """Generate HTML for a single segment."""
    character = seg.get("character", "shovel")
    char_info = CHARACTERS.get(character, {"name": character.title(), "role": "", "color": "#475569"})

    # Read segment text
    text_file = os.path.join(script_dir, seg["file"])
    if os.path.exists(text_file):
        with open(text_file) as f:
            text = f.read().strip()
    else:
        text = f"[Segment file not found: {seg['file']}]"

    # Build sources HTML
    sources_html = ""
    if seg.get("sources"):
        source_links = []
        for src in seg["sources"]:
            title = escape(src.get("title", "Source"))
            url = src.get("url", "")
            if url:
                source_links.append(f'<a class="source-link" href="{escape(url)}" target="_blank" rel="noopener">{title}</a>')
            else:
                source_links.append(f'<span class="source-link">{title}</span>')
        if source_links:
            sources_html = f"""
<div class="sources">
<div class="sources-label">Sources</div>
{"".join(source_links)}
</div>"""

    return f"""<div class="segment" style="border-left-color: {char_info['color']}">
<div class="segment-header">
<span class="character-name" style="color: {char_info['color']}">{char_info['name']}</span>
<span class="character-role">{char_info['role']}</span>
</div>
<div class="segment-text">{escape(text)}</div>{sources_html}
</div>"""


def generate_show_notes(manifest, script_dir, audio_url, broadcast_date):
    """Generate complete HTML show notes page."""
    segments_html = "\n".join(
        generate_segment_html(seg, script_dir)
        for seg in manifest
    )

    # Format date display
    try:
        dt = date.fromisoformat(broadcast_date)
        date_display = dt.strftime("%A, %B %-d, %Y")
    except ValueError:
        date_display = broadcast_date

    return HTML_TEMPLATE.format(
        date=broadcast_date,
        date_display=date_display,
        audio_url=audio_url,
        segments_html=segments_html,
    )


def main():
    parser = argparse.ArgumentParser(description="Generate HTML show notes")
    parser.add_argument("--manifest", required=True, help="Path to manifest.json")
    parser.add_argument("--audio", required=True, help="Audio file URL/path (for <audio> tag)")
    parser.add_argument("--output", "-o", required=True, help="Output HTML file")
    parser.add_argument("--date", default=str(date.today()), help="Broadcast date")

    args = parser.parse_args()

    with open(args.manifest) as f:
        manifest = json.load(f)

    script_dir = os.path.dirname(os.path.abspath(args.manifest))

    html = generate_show_notes(manifest, script_dir, args.audio, args.date)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(html)

    print(f"Show notes: {args.output} ({len(manifest)} segments)", file=sys.stderr)


if __name__ == "__main__":
    main()
